version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__TIMEOUT=60
      - QDRANT__STORAGE__OPTIMIZERS__DEFAULT_SEGMENT_NUMBER=6
      - QDRANT__STORAGE__OPTIMIZERS__MEMMAP_THRESHOLD_KB=20000
      - QDRANT__STORAGE__OPTIMIZERS__INDEXING_THRESHOLD_KB=0
      - QDRANT__STORAGE__OPTIMIZERS__VACUUM_MIN_VECTOR_NUMBER=1000
      - QDRANT__STORAGE__OPTIMIZERS__DEFAULT_FULL_SCAN_THRESHOLD=10000
      - QDRANT__STORAGE__PERFORMANCE__MEMMAP_THRESHOLD_KB=1000
      - QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_THREADS=0
    restart: always

  mem0-ollama:
    build: .
    ports:
      - "8000:8000"  # Web interface and API on port 8000
    environment:
      - MEM0_HOST=http://qdrant:6333
      - OLLAMA_HOST=http://host.docker.internal:11434
      - DEFAULT_MODEL=llama3
      - ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
    depends_on:
      - qdrant

volumes:
  qdrant-data:
